data: data/raw

data_ingestion:
  root_dir: data/
  source_url: https://drive.google.com/file/d/1ZF74F8h_419Lf-jK-k9TRMHY1GazwSQd/view?usp=drive_link
  zip_path: data/raw/data.zip
  extract_path: data/processed


prepare_base_model:
  root_dir: models/prepare_base_model
  base_model_path: models/prepare_base_model/base_model.h5
  updated_base_model_path: models/prepare_base_model/base_model_updated.h5

training:
  root_dir: models/training
  trained_model_path: models/training/model.h5